### ISSUE TITLE
storage nginx default setting error

### ISSUE THREAD

**Issue by tzpeng** [SlaSerX/stalker#27]
https://linuxhelps.net/configs/other/default

server {
    listen       80;
    server_name  localhost;
 
    location / {
        proxy_pass http://127.0.0.1:88/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
 
    location ~* \.(mpg|mpeg|avi|ts|mkv|mp4|mov|m2ts|flv|m4v|srt|sub|ass)$ {
 
        secure_link $arg_st,$arg_e;
        secure_link_md5 "supersecret$uri$remote_addr$arg_e"; # you can change secret "supersecret" in the portal config - nginx_secure_link_secret
 
        if ($secure_link = "") {
            return 403;
        }
 
        if ($secure_link = "0") {
            return 410;
        }
 
        send_timeout 6h;
        root /var/www;  #  root /var/www/html; 
    }
}

**Comment by tzpeng** [comment]
ln -s /media/raid0/mac/ /var/www/media/storage
ln -s /media/raid0/mac/ /var/www/media/bb3

**Comment by chuckomat** [comment]
Hi, a marvelous script work, have you fixed these above with your new 1.26?
I have setup the MW + Storage today, configured  config.php added the (wrong) links and are facing problems actually to connect both servers correctly together.

**Comment by tzpeng** [comment]
please  use a client login your MW+ server , play a movie , check the MW+ and Storage nginx log.

**Comment by chuckomat** [comment]
I'am actually have the problem to configure the Video club -> Movie-List -> Add file -> 
Example: ffmpeg http://anon.nasa-global.edgesuite.net/HD_downloads/135_launch_720p.wmv
I have stored a TS movie here in the storage server: /media/raid0/storage/ folder
assigned bb3... and storage following your links . This one doesn't work:
ffmpeg http://192.168.0.84/media/raid0/storage/Depeche_Mode__Live_in_Berlin.ts   Ministra Portal gives:
No media info Failed. Unable to probe http://192.168.0.84/media/raid0/stor...
The Infomir install manual o0nline doesn't explain which and what to enter to connect the storage correctly.

**Comment by chuckomat** [comment]
a tipp for the script: ask for the ip address during installation a) for the Ministra server (catch it automatically and insertion b) manually for the storage server - or for both vice versa?). Because both Linux should have been alread setup at least with one ethernet port to the common GbE switch
Than insert them into the config files automatically ;-).  -> Makes life easier as Plug&Play.

**Comment by tzpeng** [comment]
if config Storage server success  .
Video club - add movie - next next - finish Storage server will auto create the movie folder, finally upload the movie file to the folder

**Comment by chuckomat** [comment]
there is no movie folder creation neither in 'bb3' nor in 'storage' (links) nor in /media/raid0/storage etc...
I have uploaded some to TS files to  
/media/raid0/storage folder (all are 777 owner stalker (thats the sudo user)
Admin -> Storage - 
ID | Title | IP | Home directory | Maximum users | Status |  
-- | -- | -- | -- | -- | -- | --
1 | bb3 | 192.168.0.84 | /media/raid0/mac/ | 50



Log from search
Feb 06, 2019 13:04 | Result cannot be decoded. Result:    EMPTy

**Comment by tzpeng** [comment]
https://wiki.infomir.eu/eng/ministra-tv-platform/ministra-installation-guide/ministra-tv-platform-installation#MinistraTVPlatforminstallation-3ConfigurationoftheStorage(separateserver)

**Comment by chuckomat** [comment]
yes exactly. And all of these are partly bullshit for endusers because full of mistakes and not understandable descriptions only to confuse people: Sometimes you do now know which files on what machine you should modify because you have them on both MW + storage-server: All Apaches and all php's and all Nginx. So a full install incl. timeshift / api / apps / records Video-Club is almost making your brain shaking. Same critics for the security chapter ;-). If reading that, you'll becoming mad.

**Comment by chuckomat** [comment]
detected some more:
Apache2: /sites_enabled/000-default.config should sym-link the 000-default.conf to /sites_available/
but both are different: Virtual host stays at 80 instead of 88 (needed for Nginx). 
In particular if you run the install.sh a 2nd time it might not be consistent when checking files are already their?
A 'sl' failure in line: 191 (storage script setup):
-----------
cd /var/www/html/stalker_portal/storage/
chmod a+x install.sh
./install.sh

sleep 1
sl
sleep 1
---------------
returns an error - or is this intention?
