### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by rijotech** [SlaSerX/stalker#9]
I'm getting.
./install: c+=20:  not found

**Comment by SlaSerX** [comment]
cat /etc/*-release and paste

На 27.02.2018 г. 0:45 "Ange Rijo" <notifications@github.com> написа:

I'm getting.
./install: c+=20: not found

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/SlaSerX/stalker/issues/9>, or mute the thread

**Comment by SlaSerX** [comment]
Not answer
